#!/usr/bin/env bash

. bootstrap

import "infill" "renofile"

cd "$INFILL_DIR"

info "update $INFILL_DIR"
exists git || abort "Requires git for update"
[[ -d .git ]] || abort "$INFILL_DIR is not managed by git."

git pull

if [[ ! ${1:-} ]]; then
  while readline name; do
    # shellcheck disable=SC2154
    is_installed "$name" || continue
    info "update $name"
    load_renofile_env "$name"
    run_renofile "$name" "update"
  done < <(list_infill --feature)
else
  for name in "$@"; do
    is_installed "$name" || abort "Not installed feature '$name'"
    info "update $name"
    load_renofile_env "$name"
    run_renofile "$name" "update"
  done
fi
