#!/usr/bin/env bash

. bootstrap

project=$(reno-properties PROJECT)

stdout=""
for option in "$@"; do
  case $option in
    --stdout) shift; stdout=1 ;;
    *) break
  esac
done

generate() {
  local file=$1
  local data=$2

  if [[ $stdout ]];then
    puts "$data"
    return 0
  fi

  if [[ -e $file ]]; then
    reno-yesno "Already exists file. Overwrite it? [$file] " || return 1
  fi

  run mkfile "$file" "$data"
  info "$file generated."
}

generate_gitignore() {
  generate "$INFILL_DIR/.gitignore" "$(cat <<DATA
# Do not recommend the management of secret files.
id_rsa
id_dsa
id_ecdsa
identity
*.ppk
DATA
  )"
}

generate_readme() {
  generate "$INFILL_DIR/README.md" "$(cat <<DATA
This is an infill directory of the reno a home directory management tool.

Infill directory might be contained personal data.

Please be careful when you fork.

If you are interested in the reno, please refer to $project
DATA
  )"
}

generate_setup() {
  local reno_repo=$(reno-properties REPOSITORY)
  local infill_repo="YOUR-INFILL-REPOSITORY"
  local infill_archive="YOUR-INFILL-ARCHIVE"
  local installer=$(reno-properties INSTALLER)

  if ! exists git; then
    warn "infill repository not detected. [git not found]"
  elif [[ ! -e "$INFILL_DIR" ]]; then
    warn "infill repository not detected. [infill directory '$INFILL_DIR' not found]"
  else
    infill_repo=$(git -C "$INFILL_DIR" config --get remote.origin.url)
  fi

  generate "$INFILL_DIR/setup.sh" "$(cat <<DATA
#!/usr/bin/env bash

RENO_REPO="$reno_repo"
INSTALLER="$installer"
INFILL_REPO="$infill_repo"
INFILL_ARCHIVE="$infill_archive"

DATA
cat <<'DATA'
RENO_DIR="$HOME/.reno"
INFILL_DIR="$HOME/.infill"

if type git > /dev/null 2>&1; then
  if [[ -e $RENO_DIR ]]; then
    echo "Found reno directory. skipping reno installation."
  else
    git clone $RENO_REPO $RENO_DIR
    $RENO_DIR/install.sh
  fi
  $RENO_DIR/bin/reno init $INFILL_REPO
else
  echo -n "Git not found. Do you want to import from an archive? [y/N] "
  read input
  [[ $input = "y" || $input = "Y" ]] || exit 1
  if type curl > /dev/null 2>&1; then
    bash -c "$(curl -L $INSTALLER)"
  elif type wget > /dev/null 2>&1; then
    bash -c "$(wget -O - $INSTALLER)"
  else
    echo "Not found git, wget, curl. Aborting"
    exit 1
  fi
  $RENO_DIR/bin/reno init $INFILL_ARCHIVE --type archive
fi
DATA
  )"

  chmod +x "$INFILL_DIR/setup.sh"
}

func="generate_${1:-}"

exists "$func" || abort "Unknown generator name '$1'"

$func
