#!/usr/bin/env bash

. bootstrap

import "infill" "feature" "renofile" "renoattributes" "template"

name=$1
shift

exists_feature "$name" || abort "Not found feature '$name'"

for option in "$@"; do
  case $option in
    --) shift; break ;;
    *) abort "no such option '$option'"
  esac
done

load_renofile_env "$name"

run_renofile "$name" "uninstall:before" "$@"

renoattributes=$(readfile "$INFILL_DIR/$name/.renoattributes")

while readline file; do
  src="$INFILL_DIR/$name/$file"
  dest="$HOME/$file"

  attr=$(attributes_matching "$file" <<< "$renoattributes")
  get_attr "$attr" mode mask

  if [[ -e $dest ]]; then
    result=$(compare_feature_file "$src" "$dest") && :
    if [[ $result ]]; then
      run rm "$dest"
    else
      if [[ $mode = "tmpl" ]]; then
        if [[ "$(template "$src")" = "$(readfile "$dest")" ]]; then
          run rm "$dest"
        fi
      fi
    fi
  elif [[ -L $dest ]]; then
    run rm "$dest" # broken symlink
  fi
done < <(find_feature_files "$name")

run_renofile "$name" "uninstall" "$@"
run_renofile "$name" "uninstall:after" "$@"

run rm "$INFILL_INSTALLED_DIR/$name"
