#!/usr/bin/env bash

set -eu

cd "${0%/*}/$1"

image="reno-installer-test-$1"

docker build -t "$image" .

SSH_OPTS="-v $(readlink -f $SSH_AUTH_SOCK):/ssh-agent --env SSH_AUTH_SOCK=/ssh-agent"

docker run $SSH_OPTS --env-file ../env -t --rm "$image"
